name: CI/CD K3s

on:
  push:
    branches: ["main"]

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

      - uses: azure/setup-kubectl@v4

      - run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_FILE }}" > $HOME/.kube/config
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl set image deployment/flask-app flask-app=${{ env.IMAGE }}
